import TodoList from "@/components/TodoList";
import { useGetAllQuery } from "@/types/generated/generated-types";
import { Box, Center, Flex, Heading } from "@chakra-ui/react";
import { Inter } from "@next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { data } = useGetAllQuery();

  return (
    <>
      <Head>
        <title>Appsync Cdk Sample</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Center>
          <Heading>Appsync Cdk Sample</Heading>
        </Center>
      </Box>
      <main>
        <Flex m={4}>
          <TodoList todos={data?.getAll!} />
        </Flex>
      </main>
    </>
  );
}
